import { expect, test, type Page } from "@playwright/test";
import { browseUrl, escapeRe } from "./helpers";

const tile = (page: Page, name: string) => page.getByRole("gridcell", { name: new RegExp(`^${escapeRe(name)},`) });

test.describe("grid previews", () => {
  test("tiles show a video frame, text snippets, and the icon for everything else", async ({ page, isMobile, browserName }) => {
    test.skip(isMobile, "Needs every tile near the fold; a phone shows two. The below-the-fold test covers lazy loading.");
    const errors: string[] = [];
    page.on("console", (m) => {
      if (m.type() === "error") errors.push(m.text());
    });
    page.on("pageerror", (e) => errors.push(e.message));
    const pdfThumb = page.waitForResponse((r) => r.url().includes("/api/thumb?key=Factory%2Fsummary.pdf"));

    await page.goto(browseUrl("Factory/") + "&view=grid");

    // The MP4 gets a poster frame generated by ffmpeg, which really decoded.
    const mp4 = tile(page, "episode_0001_pick_and_place.mp4");
    const frame = mp4.locator("img");
    await expect(frame).toHaveAttribute("src", /\/api\/thumb\?key=Factory%2Fepisode_0001/);
    await expect.poll(() => frame.evaluate((img: HTMLImageElement) => (img.complete ? img.naturalWidth : 0))).toBeGreaterThan(0);
    // Decorative: the tile's own label names the file.
    await expect(frame).toHaveAttribute("alt", "");

    // Markdown and JSON tiles show their first lines.
    await expect(tile(page, "README.md").locator("pre")).toContainText("# Factory episodes");
    await expect(tile(page, "episodes_index.json").locator("pre")).toContainText('"episodes"');

    // A file with no preview keeps its icon and never asks for one.
    const bin = tile(page, "sensor_dump.bin");
    await expect(bin.locator("svg").first()).toBeVisible();
    await expect(bin.locator("img, pre")).toHaveCount(0);

    // The PDF gets its first page where pdftoppm is installed; otherwise a quiet 204 and its icon.
    const pdf = await pdfThumb;
    expect([200, 204]).toContain(pdf.status());
    if (pdf.status() === 204) {
      await expect(tile(page, "summary.pdf").locator("img")).toHaveCount(0);
    }

    // Previews never resize tiles: the video tile matches a tile that only has an icon.
    const [a, b] = await Promise.all([mp4.boundingBox(), bin.boundingBox()]);
    expect(a?.height).toBe(b?.height);
    // Firefox lays out in 1/60 px units, so grid columns can differ by one unit.
    const unit = browserName === "firefox" ? 1 / 60 : 0;
    expect(Math.abs(a!.width - b!.width)).toBeLessThanOrEqual(unit);

    expect(errors).toEqual([]);
  });

  test("tiles far below the fold don't load previews", async ({ page }) => {
    const thumbs: string[] = [];
    page.on("request", (r) => {
      if (r.url().includes("/api/thumb") || r.url().includes("/api/files/text")) thumbs.push(r.url());
    });
    // A tiny window: only the first row or two is anywhere near the viewport.
    await page.setViewportSize({ width: 700, height: 420 });
    await page.goto(browseUrl("Factory/") + "&view=grid");
    await expect(tile(page, "calibration.zip")).toBeVisible();
    await page.waitForTimeout(1500);
    // Files sort after folders by name; site_overview.jpg and summary.pdf are near the end.
    expect(thumbs.some((u) => u.includes("summary.pdf"))).toBe(false);

    // Scrolled into view, they load.
    await page.getByRole("grid").evaluate((el) => el.scrollTo(0, el.scrollHeight));
    await expect.poll(() => thumbs.some((u) => u.includes("summary.pdf"))).toBe(true);
  });

  test("images show a scaled copy, and a second visit asks the server for nothing new", async ({ page }) => {
    // Chromium's own record of where each response came from: the network, or its cache.
    const cdp = await page.context().newCDPSession(page);
    await cdp.send("Network.enable");
    const thumbs = new Map<string, { url: string; status?: number; cached?: boolean }>();
    cdp.on("Network.requestWillBeSent", (e) => {
      if (e.request.url.includes("/api/thumb")) thumbs.set(e.requestId, { url: e.request.url });
    });
    cdp.on("Network.requestServedFromCache", (e) => {
      const t = thumbs.get(e.requestId);
      if (t) t.cached = true;
    });
    cdp.on("Network.responseReceived", (e) => {
      const t = thumbs.get(e.requestId);
      if (!t) return;
      t.status = e.response.status;
      t.cached ||= Boolean(e.response.fromDiskCache);
    });

    const frames = ["episode_0001_pick_and_place.mp4", "frame_0001.png", "site_overview.jpg"];
    const loaded = async () => {
      for (const name of frames) {
        const img = tile(page, name).locator("img");
        await expect(img).toHaveAttribute("src", /\/api\/thumb\?key=/);
        await expect.poll(() => img.evaluate((el: HTMLImageElement) => (el.complete ? el.naturalWidth : 0))).toBeGreaterThan(0);
      }
    };

    const first = page.waitForResponse((r) => r.url().includes("/api/thumb?key=Factory%2Fframe_0001.png"));
    await page.goto(browseUrl("Factory/") + "&view=grid");
    const png = await first;
    expect(png.status()).toBe(200);
    // Tile-sized: far smaller than the 215 KB original, and kept by the browser for good.
    expect(Number(png.headers()["content-length"])).toBeLessThan(100_000);
    expect(png.headers()["cache-control"]).toContain("immutable");
    await loaded();

    thumbs.clear();
    await page.goto(browseUrl("Factory/") + "&view=grid");
    await loaded();
    // A 204 (the PDF, where pdftoppm isn't installed) is "no preview", asked again on the next visit.
    const seen = [...thumbs.values()].filter((t) => t.status !== 204);
    expect(seen.length).toBeGreaterThanOrEqual(frames.length);
    // Every thumbnail came from the browser's cache, or at most a 304 (nothing generated or sent again).
    for (const t of seen) expect(t.cached || t.status === 304, t.url).toBe(true);
  });
});
